# Generated by Django 2.2 on 2023-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_username', models.CharField(max_length=200)),
                ('reviewed_ride', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rides',
            name='ride_image',
            field=models.ImageField(default='ride_images/default.jpg', upload_to='ride_images'),
        ),
    ]
