# Generated by Django 2.2 on 2023-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20231114_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='ride_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
